<?php
// Exit if accessed directly.
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Returns an array of Font Awesome 7 FREE icon classes.
 * We MUST include the style prefix (fas, far, fab).
 */
return [
    // --- Solid (fas) ---
    'fas fa-user', 'fas fa-star', 'fas fa-check', 'fas fa-times', 'fas fa-home',
    'fas fa-cog', 'fas fa-envelope', 'fas fa-heart', 'fas fa-search', 'fas fa-bell',
    'fas fa-bars', 'fas fa-trash', 'fas fa-edit', 'fas fa-info-circle', 'fas fa-question-circle',
    'fas fa-arrow-left', 'fas fa-arrow-right', 'fas fa-arrow-up', 'fas fa-arrow-down',
    'fas fa-chevron-left', 'fas fa-chevron-right', 'fas fa-chevron-up', 'fas fa-chevron-down',
    'fas fa-calendar-alt', 'fas fa-clock', 'fas fa-folder', 'fas fa-folder-open', 'fas fa-link',
    'fas fa-paperclip', 'fas fa-map-marker-alt', 'fas fa-phone', 'fas fa-image', 'fas fa-camera',
    'fas fa-video', 'fas fa-play', 'fas fa-pause', 'fas fa-stop', 'fas fa-plus', 'fas fa-minus',
    'fas fa-exclamation-triangle', 'fas fa-wifi', 'fas fa-power-off', 'fas fa-lock', 'fas fa-unlock',
    'fas fa-tag', 'fas fa-tags', 'fas fa-book', 'fas fa-bookmark', 'fas fa-print', 'fas fa-font',
    'fas fa-bold', 'fas fa-italic', 'fas fa-underline', 'fas fa-strikethrough', 'fas fa-align-left',
    'fas fa-align-center', 'fas fa-align-right', 'fas fa-align-justify', 'fas fa-list', 'fas fa-list-ol',
    'fas fa-list-ul', 'fas fa-indent', 'fas fa-outdent', 'fas fa-quote-left', 'fas fa-quote-right',
    'fas fa-code', 'fas fa-code-branch', 'fas fa-terminal', 'fas fa-download', 'fas fa-upload',
    'fas fa-share', 'fas fa-reply', 'fas fa-reply-all', 'fas fa-location-arrow', 'fas fa-crosshairs',
    'fas fa-ban', 'fas fa-gift', 'fas fa-leaf', 'fas fa-fire', 'fas fa-eye', 'fas fa-eye-slash',
    'fas fa-plane', 'fas fa-calendar-days', 'fas fa-shuffle', 'fas fa-comment', 'fas fa-magnet',
    'fas fa-retweet', 'fas fa-cart-shopping', 'fas fa-folder', 'fas fa-folder-open', 'fas fa-chart-bar',
    'fas fa-camera-retro', 'fas fa-key', 'fas fa-gears', 'fas fa-comments', 'fas fa-star-half',
    'fas fa-arrow-right-from-bracket', 'fas fa-thumbtack', 'fas fa-arrow-up-right-from-square',
    'fas fa-arrow-right-to-bracket', 'fas fa-trophy', 'fas fa-headphones', 'fas fa-volume-off',
    'fas fa-volume-low', 'fas fa-volume-high', 'fas fa-qrcode', 'fas fa-barcode', 'fas fa-book-open',
    'fas fa-briefcase', 'fas fa-certificate', 'fas fa-wrench', 'fas fa-list-check', 'fas fa-filter',
    'fas fa-globe', 'fas fa-umbrella', 'fas fa-paste', 'fas fa-lightbulb', 'fas fa-cloud', 'fas fa-flask',
    'fas fa-scissors', 'fas fa-copy', 'fas fa-floppy-disk', 'fas fa-square', 'fas fa-table', 'fas fa-truck',
    'fas fa-money-bill', 'fas fa-user-doctor', 'fas fa-stethoscope', 'fas fa-suitcase', 'fas fa-bell',
    'fas fa-mug-saucer', 'fas fa-hospital', 'fas fa-truck-medical', 'fas fa-suitcase-medical',
    'fas fa-building-columns', 'fas fa-graduation-cap', 'fas fa-language', 'fas fa-fax', 'fas fa-building',
    'fas fa-child', 'fas fa-paw', 'fas fa-cube', 'fas fa-cubes', 'fas fa-recycle', 'fas fa-car', 'fas fa-taxi',
    'fas fa-tree', 'fas fa-database', 'fas fa-file-pdf', 'fas fa-file-word', 'fas fa-file-excel',
    'fas fa-file-powerpoint', 'fas fa-file-image', 'fas fa-file-zipper', 'fas fa-file-audio',
    'fas fa-file-video', 'fas fa-file-code', 'fas fa-life-ring', 'fas fa-circle-notch', 'fas fa-paper-plane',
    'fas fa-history', 'fas fa-heading', 'fas fa-paragraph', 'fas fa-sliders', 'fas fa-share-nodes',
    'fas fa-bomb', 'fas fa-futbol', 'fas fa-tty', 'fas fa-binoculars', 'fas fa-plug', 'fas fa-newspaper',
    'fas fa-calculator', 'fas fa-bell-slash', 'fas fa-copyright', 'fas fa-paintbrush', 'fas fa-cake-candles',
    'fas fa-chart-area', 'fas fa-chart-pie', 'fas fa-chart-line', 'fas fa-toggle-off', 'fas fa-toggle-on',
    'fas fa-bicycle', 'fas fa-bus', 'fas fa-closed-captioning', 'fas fa-cart-plus', 'fas fa-cart-arrow-down',
    'fas fa-ship', 'fas fa-user-secret', 'fas fa-motorcycle', 'fas fa-street-view', 'fas fa-heart-pulse',
    'fas fa-venus', 'fas fa-mars', 'fas fa-server', 'fas fa-user-plus', 'fas fa-user-xmark', 'fas fa-bed',
    'fas fa-train', 'fas fa-train-subway', 'fas fa-battery-full', 'fas fa-battery-three-quarters',
    'fas fa-battery-half', 'fas fa-battery-quarter', 'fas fa-battery-empty', 'fas fa-arrow-pointer',
    'fas fa-i-cursor', 'fas fa-object-group', 'fas fa-object-ungroup', 'fas fa-note-sticky', 'fas fa-clone',
    'fas fa-scale-balanced', 'fas fa-hourglass-start', 'fas fa-hourglass-half', 'fas fa-hourglass-end',
    'fas fa-hourglass', 'fas fa-hand-back-fist', 'fas fa-hand', 'fas fa-hand-scissors', 'fas fa-hand-lizard',
    'fas fa-hand-spock', 'fas fa-hand-pointer', 'fas fa-hand-peace', 'fas fa-trademark', 'fas fa-registered',
    'fas fa-tv', 'fas fa-calendar-plus', 'fas fa-calendar-minus', 'fas fa-calendar-xmark',
    'fas fa-calendar-check', 'fas fa-industry', 'fas fa-map-pin', 'fas fa-signs-post', 'fas fa-map',
    'fas fa-message', 'fas fa-circle-pause', 'fas fa-circle-stop', 'fas fa-bag-shopping',
    'fas fa-basket-shopping', 'fas fa-universal-access', 'fas fa-person-walking-with-cane',
    'fas fa-audio-description', 'fas fa-phone-volume', 'fas fa-braille', 'fas fa-ear-listen',
    'fas fa-hands-asl-interpreting', 'fas fa-ear-deaf', 'fas fa-hands', 'fas fa-eye-low-vision',
    'fas fa-handshake', 'fas fa-envelope-open', 'fas fa-address-book', 'fas fa-address-card',
    'fas fa-circle-user', 'fas fa-id-badge', 'fas fa-id-card', 'fas fa-temperature-full',
    'fas fa-temperature-three-quarters', 'fas fa-temperature-half', 'fas fa-temperature-quarter',
    'fas fa-temperature-empty', 'fas fa-shower', 'fas fa-bath', 'fas fa-podcast', 'fas fa-window-maximize',
    'fas fa-window-minimize', 'fas fa-window-restore', 'fas fa-square-xmark', 'fas fa-microchip',
    'fas fa-snowflake', 'fas fa-spoon', 'fas fa-utensils', 'fas fa-rotate-left', 'fas fa-trash-can',
    'fas fa-rotate', 'fas fa-stopwatch', 'fas fa-right-from-bracket', 'fas fa-right-to-bracket',
    'fas fa-rotate-right', 'fas fa-poo', 'fas fa-images', 'fas fa-pencil', 'fas fa-pen', 'fas fa-pen-clip',
    'fas fa-down-long', 'fas fa-left-long', 'fas fa-right-long', 'fas fa-up-long', 'fas fa-file-pen',
    'fas fa-maximize', 'fas fa-clipboard', 'fas fa-left-right', 'fas fa-up-down', 'fas fa-circle-down',
    'fas fa-circle-left', 'fas fa-circle-right', 'fas fa-circle-up', 'fas fa-up-right-from-square',
    'fas fa-square-up-right', 'fas fa-right-left', 'fas fa-repeat', 'fas fa-code-commit', 'fas fa-code-merge',
    'fas fa-desktop', 'fas fa-gem', 'fas fa-turn-down', 'fas fa-turn-up', 'fas fa-lock-open',
    'fas fa-location-dot', 'fas fa-microphone-lines', 'fas fa-mobile-screen-button', 'fas fa-mobile',
    'fas fa-mobile-screen', 'fas fa-money-bill-1', 'fas fa-phone-slash', 'fas fa-image-portrait', 'fas fa-reply',
    'fas fa-shield-halved', 'fas fa-tablet-screen-button', 'fas fa-tablet', 'fas fa-ticket-simple',
    'fas fa-rectangle-xmark', 'fas fa-down-left-and-up-right-to-center',
    'fas fa-up-right-and-down-left-from-center', 'fas fa-anchor',
    // --- Add more solid icons as needed ---

    // --- Regular (far) ---
    'far fa-heart', 'far fa-star', 'far fa-user', 'far fa-clock', 'far fa-flag', 'far fa-bell',
    'far fa-bookmark', 'far fa-image', 'far fa-images', 'far fa-copy', 'far fa-paste', 'far fa-square',
    'far fa-circle', 'far fa-envelope', 'far fa-envelope-open', 'far fa-comment', 'far fa-comments',
    'far fa-thumbs-up', 'far fa-thumbs-down', 'far fa-calendar', 'far fa-calendar-days',
    'far fa-calendar-check', 'far fa-calendar-minus', 'far fa-calendar-plus', 'far fa-calendar-xmark',
    'far fa-file', 'far fa-file-lines', 'far fa-file-pdf', 'far fa-file-word', 'far fa-file-excel',
    'far fa-file-powerpoint', 'far fa-file-image', 'far fa-file-zipper', 'far fa-file-audio',
    'far fa-file-video', 'far fa-file-code', 'far fa-folder', 'far fa-folder-open', 'far fa-lemon',
    'far fa-snowflake', 'far fa-lightbulb', 'far fa-sun', 'far fa-moon', 'far fa-hospital', 'far fa-circle-play',
    'far fa-circle-pause', 'far fa-circle-stop', 'far fa-square-caret-down', 'far fa-square-caret-up',
    'far fa-square-caret-right', 'far fa-square-caret-left', 'far fa-circle-dot', 'far fa-registered',
    'far fa-copyright', 'far fa-closed-captioning', 'far fa-object-group', 'far fa-object-ungroup',
    'far fa-note-sticky', 'far fa-address-book', 'far fa-address-card', 'far fa-circle-user',
    'far fa-id-badge', 'far fa-id-card', 'far fa-window-maximize', 'far fa-window-minimize',
    'far fa-window-restore', 'far fa-square-check', 'far fa-square-minus', 'far fa-square-plus',
    'far fa-face-smile', 'far fa-face-frown', 'far fa-face-meh', 'far fa-face-angry', 'far fa-face-dizzy',
    'far fa-face-flushed', 'far fa-face-frown-open', 'far fa-face-grimace', 'far fa-face-grin',
    'far fa-face-grin-wide', 'far fa-face-grin-beam', 'far fa-face-grin-beam-sweat', 'far fa-face-grin-hearts',
    'far fa-face-grin-squint', 'far fa-face-grin-squint-tears', 'far fa-face-grin-stars',
    'far fa-face-grin-tears', 'far fa-face-grin-tongue', 'far fa-face-grin-tongue-squint',
    'far fa-face-grin-tongue-wink', 'far fa-face-grin-wink', 'far fa-face-kiss', 'far fa-face-kiss-beam',
    'far fa-face-kiss-wink-heart', 'far fa-face-laugh', 'far fa-face-laugh-beam', 'far fa-face-laugh-squint',
    'far fa-face-laugh-wink', 'far fa-face-meh-blank', 'far fa-face-rolling-eyes', 'far fa-face-sad-cry',
    'far fa-face-sad-tear', 'far fa-face-smile-beam', 'far fa-face-smile-wink', 'far fa-face-surprise',
    'far fa-face-tired', 'far fa-hand-back-fist', 'far fa-hand', 'far fa-hand-lizard', 'far fa-hand-peace',
    'far fa-hand-point-down', 'far fa-hand-point-left', 'far fa-hand-point-right', 'far fa-hand-point-up',
    'far fa-hand-pointer', 'far fa-hand-scissors', 'far fa-hand-spock',
    // --- Add more regular icons as needed ---

    // --- Brands (fab) ---
    'fab fa-wordpress', 'fab fa-elementor', 'fab fa-facebook', 'fab fa-twitter', 'fab fa-instagram',
    'fab fa-linkedin', 'fab fa-youtube', 'fab fa-github', 'fab fa-gitlab', 'fab fa-slack',
    'fab fa-figma', 'fab fa-google', 'fab fa-microsoft', 'fab fa-apple', 'fab fa-android',
    'fab fa-windows', 'fab fa-chrome', 'fab fa-firefox', 'fab fa-safari', 'fab fa-edge',
    'fab fa-aws', 'fab fa-docker', 'fab fa-git-alt', 'fab fa-js', 'fab fa-html5', 'fab fa-css3-alt',
    'fab fa-react', 'fab fa-vuejs', 'fab fa-angular', 'fab fa-node-js', 'fab fa-npm', 'fab fa-python',
    'fab fa-php', 'fab fa-laravel', 'fab fa-symfony', 'fab fa-java', 'fab fa-swift', 'fab fa-docker',
    'fab fa-pinterest', 'fab fa-reddit', 'fab fa-tumblr', 'fab fa-whatsapp', 'fab fa-skype',
    'fab fa-discord', 'fab fa-telegram', 'fab fa-viber', 'fab fa-snapchat', 'fab fa-tiktok',
    'fab fa-spotify', 'fab fa-soundcloud', 'fab fa-paypal', 'fab fa-stripe', 'fab fa-cc-visa',
    'fab fa-cc-mastercard', 'fab fa-cc-amex', 'fab fa-cc-paypal', 'fab fa-cc-stripe', 'fab fa-cc-apple-pay',
    'fab fa-amazon', 'fab fa-ebay', 'fab fa-google-play', 'fab fa-app-store', 'fab fa-app-store-ios',
    'fab fa-dribbble', 'fab fa-behance', 'fab fa-medium', 'fab fa-stack-overflow', 'fab fa-stack-exchange',
    'fab fa-codepen', 'fab fa-jsfiddle', 'fab fa-dropbox', 'fab fa-google-drive', 'fab fa-trello',
    'fab fa-glide', 'fab fa-glide-g', 'fab fa-vimeo', 'fab fa-vimeo-v', 'fab fa-slideshare', 'fab fa-twitch',
    'fab fa-steam', 'fab fa-playstation', 'fab fa-xbox', 'fab fa-battle-net', 'fab fa-itch-io',
    'fab fa-wikipedia-w', 'fab fa-imdb', 'fab fa-waze', 'fab fa-meetup', 'fab fa-airbnb', 'fab fa-uber', 'fab fa-lyft',
    'fab fa-font-awesome', 'fab fa-bootstrap', 'fab fa-reacteurope', 'fab fa-gulp', 'fab fa-grunt',
    'fab fa-node', 'fab fa-sass', 'fab fa-less', 'fab fa-yarn',
    // --- Add more brand icons as needed ---
];